"""create judgments table

Revision ID: 0dc0d29e26da
Revises: b30f6ff44954
Create Date: 2026-09-01 09:48:00.821817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc0d29e26da'
down_revision: Union[str, Sequence[str], None] = 'b30f6ff44954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('judgment_type', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgments_case_id'), 'judgments', ['case_id'], unique=True)
    op.create_index(op.f('ix_judgments_id'), 'judgments', ['id'], unique=False)
    op.create_index(op.f('ix_judgments_issued_at'), 'judgments', ['issued_at'], unique=False)
    op.create_index(op.f('ix_judgments_judge_id'), 'judgments', ['judge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgments_judge_id'), table_name='judgments')
    op.drop_index(op.f('ix_judgments_issued_at'), table_name='judgments')
    op.drop_index(op.f('ix_judgments_id'), table_name='judgments')
    op.drop_index(op.f('ix_judgments_case_id'), table_name='judgments')
    op.drop_table('judgments')
    # ### end Alembic commands ###
