"""create hearings table

Revision ID: 61a19c4db97b
Revises: 0efd1c80d61b
Create Date: 2026-09-01 09:33:42.753054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a19c4db97b'
down_revision: Union[str, Sequence[str], None] = '0efd1c80d61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hearings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('hearing_date', sa.DateTime(), nullable=False),
    sa.Column('courtroom', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'ADJOURNED', 'CANCELLED', name='hearingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hearings_case_id'), 'hearings', ['case_id'], unique=False)
    op.create_index(op.f('ix_hearings_hearing_date'), 'hearings', ['hearing_date'], unique=False)
    op.create_index(op.f('ix_hearings_id'), 'hearings', ['id'], unique=False)
    op.create_index(op.f('ix_hearings_status'), 'hearings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hearings_status'), table_name='hearings')
    op.drop_index(op.f('ix_hearings_id'), table_name='hearings')
    op.drop_index(op.f('ix_hearings_hearing_date'), table_name='hearings')
    op.drop_index(op.f('ix_hearings_case_id'), table_name='hearings')
    op.drop_table('hearings')
    # ### end Alembic commands ###
