"""create case participants table

Revision ID: c18dd0d5f50b
Revises: 8bb33d30ac41
Create Date: 2026-09-01 09:40:10.059778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18dd0d5f50b'
down_revision: Union[str, Sequence[str], None] = '8bb33d30ac41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PLAINTIFF', 'DEFENDANT', 'LAWYER', 'JUDGE', 'CLERK', 'WITNESS', 'OTHER', name='participantrole'), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_participants_case_id'), 'case_participants', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_participants_id'), 'case_participants', ['id'], unique=False)
    op.create_index(op.f('ix_case_participants_role'), 'case_participants', ['role'], unique=False)
    op.create_index(op.f('ix_case_participants_user_id'), 'case_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_participants_user_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_role'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_case_id'), table_name='case_participants')
    op.drop_table('case_participants')
    # ### end Alembic commands ###
